In [1]:
import pandas as pd

In [5]:
# Read excel file. 
# Error read_csv didnot allow e to read specific sheet name
df=pd.read_excel('Master_Sheet_Ram_V4.xlsx', sheet_name = 'Master_Sheet')

In [9]:
# Declaring dictionary data type to be converted into data frame. 
# Error The 
Dict_Data={
    'Name': ['Ram kinker', 'Ram Mohan','Ram Nayan','Ram Sharan'],
    'Age': [35,40,45,46],
    'Weight': [100, 90, 96, 100]
}

In [23]:
# Access different things related to dictionary
Dict_Data['Weight'][0]
Dict_Data['Name'][0]

Dict_Data.keys()
Dict_Data.values()
Dict_Data.items()

dict_items([('Name', ['Ram kinker', 'Ram Mohan', 'Ram Nayan', 'Ram Sharan']), ('Age', [35, 40, 45, 46]), ('Weight', [100, 90, 96, 100])])

In [18]:
df_dict=pd.DataFrame.from_dict(Dict_Data)
df_dict
df_dict.head(2)
df.tail(2)

,Study,Patient_ID,Years_Education,3-mon FU fall (0: no; 1: yes),3-mon FU DFU (0: no; 1: yes),6-mon FU fall (0: no; 1: yes),6-mon FU DFU (0: no; 1: yes),1-year FU fall (0: no; 1: yes),1-year FU DFU (0: no; 1: yes),Group (0: control; 1: intervention),...,"FUDT_L_Extension Time Reduction, %","FUDT_L_Flexion Acceleration Time Average, msec","FUDT_L_Flexion Acceleration Time CV, %","FUDT_L_Flexion Acceleration Time Reduction, %","FUDT_L_Extension Acceleration Time Average, msec","FUDT_L_Extension Acceleration Time CV, %","FUDT_L_Extension Acceleration Time Reduction, %","FUDT_L_Rate Average, reps./min","FUDT_L_Rate CV, %","FUDT_L_Rate Reduction, %"
644,VACOPD 051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
645,VA COPD 052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
# Get the column names
df.columns
# Get the types of data in the data frame
df.dtypes

Study                                               object
Patient_ID                                          object
Years_Education                                    float64
3-mon FU fall (0: no; 1: yes)                      float64
3-mon FU DFU (0: no; 1: yes)                       float64
                                                    ...
FUDT_L_Extension Acceleration Time CV, %           float64
FUDT_L_Extension Acceleration Time Reduction, %    float64
FUDT_L_Rate Average, reps./min                     float64
FUDT_L_Rate CV, %                                  float64
FUDT_L_Rate Reduction, %                           float64
Length: 874, dtype: object

In [29]:
# Understanding data is most crucial part of data science
df.describe()
# Above command give details about integer and float only. 
# However, if we want to explore the categorical variable then we should use below command.
df.describe(include='object')

,Study,Patient_ID,Race (0: American Indian; 1: Asian; 2: Black; 3: Native Hawaiian; 4: White; 5: Other),Ethnicity(0: Non-hispanic; 1: Hispanic),BL_Slowness (Not Frail: 0; Frail: 1),BL_MOCA,BL_FES-I,TUG_FU,BL_Duration_%_Standing,BL_OneDay_Duration_%_Standing
count,646,434,244,302,433,545,514,46.00,398.00,365.00
unique,646,362,26,10,4,27,54,46.00,397.00,364.00
top,SunCity18,125,Qatari,0,0,30,7,14.16,14.02,14.02
freq,1,4,41,91,221,105,43,1.00,2.00,2.00

In [38]:
df[(df['Years_Education']>10) & (df['Years_Education']>5)]

,Study,Patient_ID,Years_Education,3-mon FU fall (0: no; 1: yes),3-mon FU DFU (0: no; 1: yes),6-mon FU fall (0: no; 1: yes),6-mon FU DFU (0: no; 1: yes),1-year FU fall (0: no; 1: yes),1-year FU DFU (0: no; 1: yes),Group (0: control; 1: intervention),...,"FUDT_L_Extension Time Reduction, %","FUDT_L_Flexion Acceleration Time Average, msec","FUDT_L_Flexion Acceleration Time CV, %","FUDT_L_Flexion Acceleration Time Reduction, %","FUDT_L_Extension Acceleration Time Average, msec","FUDT_L_Extension Acceleration Time CV, %","FUDT_L_Extension Acceleration Time Reduction, %","FUDT_L_Rate Average, reps./min","FUDT_L_Rate CV, %","FUDT_L_Rate Reduction, %"
81,MCI_Itmt1,MCI001,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-12.295082,269.629630,0.167601,1.395731,195.555556,0.142769,1.700680,82.342026,0.054576,1.581054
83,MCI_Itmt3,MCI003,21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-10.526316,277.500000,0.098029,1.818182,472.500000,0.188586,-7.142857,49.272642,0.079391,1.015348
84,MCI_Itmt4,MCI004,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,MCI_Itmt5,MCI005,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-5.555556,242.758621,0.115937,-6.666667,244.137931,0.133859,-7.715356,91.264157,0.082757,2.021722
86,MCI_Itmt6,MCI006,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.571429,283.333333,0.111948,7.317073,566.666667,0.066172,0.000000,36.367023,0.107524,-6.755000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,SunCity26,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323,SunCity27,NaN,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,SunCity28,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
325,SunCity29,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,SunCity30,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Indexing with iloc